export const Types = {
  UPLOAD_NEW_IMAGE: 'UPLOAD_NEW_IMAGE',
  UPLOAD_NEW_IMAGE_SUCCESS: 'UPLOAD_NEW_IMAGE_SUCCESS',
  UPLOAD_NEW_IMAGE_FAILED: 'UPLOAD_NEW_IMAGE_FAILED',
  GET_IMAGE_LIST: 'GET_IMAGE_LIST',
  GET_IMAGE_LIST_SUCCESS: 'GET_IMAGE_LIST_SUCCESS',
  GET_IMAGE_LIST_FAILED: 'GET_IMAGE_LIST_FAILED',
  GET_IMAGE_BY_ID: 'GET_IMAGE_BY_ID',
  GET_IMAGE_BY_ID_SUCCESS: 'GET_IMAGE_BY_ID_SUCCESS',
  GET_IMAGE_BY_ID_FAILED: 'GET_IMAGE_BY_ID_FAILED'
};
